name: "Run Pester tests"

on: 
  push:
    branches:
      - donotexist
  repository_dispatch:
    types:
      - webhook

jobs:
  job-main:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      shlink:
        image: shlinkio/shlink:stable
        ports: 
          - 80:8080
        env:
          IS_HTTPS_ENABLED: false
          DEFAULT_DOMAIN: psshlink.codaamok
        options: --name shlink
    steps:
      - name: Modify DNS
        run: echo "127.0.0.1 psshlink.codaamok" | sudo tee -a /etc/hosts

      - name: Checkout repository
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true

      - name: Install codaamok.build and dependent modules, and set environment variables
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module "InvokeBuild" -Force
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          Invoke-Build -File "invoke.build.ps1" -ModuleName $ProjectName -Author $Username -Task "InstallDependencies","ImportBuildModule","SetGitHubActionEnvironmentVariables"
        shell: pwsh

      - name: Build
        run: |
          $Params = @{
            ModuleName = $env:GH_PROJECTNAME
            Author     = $env:GH_USERNAME
            Version    = $env:GitVersion_MajorMinorPatch
            NewRelease = $true
          }
          Invoke-Build -File "custom.build.ps1" @Params -Task PreBuild
          Invoke-Build -File "invoke.build.ps1" @Params
          Invoke-Build -File "custom.build.ps1" @Params -Task PostBuild
        shell: pwsh

      - name: Generate Shlink API key
        run: |
          New-BuildEnvironmentVariable -Platform "GitHubActions" -Variable @{
            "ShlinkAPIKey" = [Regex]::Match((docker exec -t shlink shlink api-key:generate --no-ansi), '([0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12})') | 
              Select-Object -ExpandProperty Value |
              ConvertTo-SecureString -AsPlainText -Force |
              ConvertFrom-SecureString
            "ShlinkServer" = "http://psshlink.codaamok"
          }
        shell: pwsh

      - name: Pester Acceptance Tests Report
        uses: zyborg/pester-tests-report@v1.5.0
        with:
          include_paths: './tests/Public/New-*.Acceptance.Tests.ps1, ./tests/Public/Get-*.Acceptance.Tests.ps1, ./tests/Public/Save-*.Acceptance.Tests.ps1, ./tests/Public/Set-ShlinkUrl.Acceptance.Tests.ps1, ./tests/Public/Set-ShlinkTag.Acceptance.Tests.ps1, ./tests/Public/Remove-*.Acceptance.Tests.ps1'
          report_name: Pester Acceptance Tests Report
          report_title: Pester Acceptance Tests Report
          output_level: detailed
          tests_fail_step: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
