name: "Test workflow dispatch"

on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  job-main:
    name: Test workflow dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: codaamok/PSShlink
          event-type: webhook